### ISSUE TITLE
 more complex routing

### ISSUE THREAD

**Issue by sloev** [trustpilot/python-lambdarest#10]
Yes og course. It was very nondescript :-)

I think it would be great if the handler supported both of the following
syntaxes:

Normal behaviour, implicitly routing `/`:
```
@lambda_handler.handle('get')
def get_this():pass
```
And more complex routings like
```
@lambda_handler.handle('get', path='/foobar')
def get_this_foobar():pass
```

**Comment by martinbuberl** [comment]
Can you please add a little bit more context on this issue.

**Comment by sloev** [comment]
Yes og course. It was very nondescript :-)

I think it would be great if the handler supported both of the following
syntaxes:

Normal behaviour, implicitly routing `/`:
```
@lambda_handler.handle('get')
def get_this():pass
```
And more complex routings like
```
@lambda_handler.handle('get', '/foobar)
def get_this_foobar():pass
```

**Comment by sloev** [comment]
Yes og course. It was very nondescript :-)

I think it would be great if the handler supported both of the following
syntaxes:

Normal behaviour, implicitly routing `/`:
```
@lambda_handler.handle('get')
def get_this():pass
```
And more complex routings like
```
@lambda_handler.handle('get', '/foobar)
def get_this_foobar():pass
```

**Comment by sloev** [comment]
https://github.com/trustpilot/python-lambdarest/pull/15

**Comment by martinbuberl** [comment]
LGTM!
