### ISSUE TITLE
Briefly mention in README how to setup api-gateway for Lambdarest lambda

### ISSUE THREAD

**Issue by sloev** [trustpilot/python-lambdarest#38]
Hi @svdgraaf, Can you maybe briefly write an update to the readme mentioning how to setup the api-gateway for using Lambdarest. I haven't been using lambdarest in production in over a year so i am a bit rusty.
Thanks for your contributions!

**Comment by grudelsud** [comment]
hi there! 

I just found this repo and was planning to give it a go for a little test, but if I may ask a little extra help in addition to what mentioned by @sloev, it'd be useful to know how to configure the lambda handler. 

e.g. with a `{proxy+}` api gateway configuration, I would normally have a `lambda.py` file containing a `def run(event, context)` function, then I would check the path value in the event object and run some function accordingly. My configuration for the lambda handler in aws would just be `lambda.run`. 

is it possible to do something equivalent with this package? how would I define the handler in the lambda configuration?

any help appreciated, thank you!

**Comment by sloev** [comment]
I am sorry for the delay @grudelsud i have emailed @svdgraaf but no answer. I havent used the projct aince 2016 so my knowledge is outdated

**Comment by grudelsud** [comment]
thank you @sloev appreciate it. No longer needed though, as I just wanted to have a simple router, and I've ended up writing one from scratch, here: https://github.com/grudelsud/alphorn

I'm also quite tempted to test zappa with flask, the serverless library scene is finally revving up 😄

**Comment by sloev** [comment]
Yeah the scene is growing. Good luck!!! 😀

søn. 18. nov. 2018 16.48 skrev grudelsud <notifications@github.com>:

**Comment by sloev** [comment]
@grudelsud you can also now use application load balancer 
http://www.devgrok.com/2019/03/create-private-microservice-using.html
here is a blogpost explaining how to do that using lambdarest
