### ISSUE TITLE
If supported, add clearer documentation for headers

### ISSUE THREAD

**Issue by mcgodes** [trustpilot/python-lambdarest#44]
Hi @svdgraaf, Can you maybe briefly write an update to the readme mentioning how to setup my APIs to respond with different headers? For example, I need to respond with the 'Access-Control-Allow-Origin' header due to CORS restrictions, and I'm struggling to find the way to do that. Aside from that, am loving the ease of use. Thanks for your contributions!

**Comment by mcgodes** [comment]
JK! Found it by reading through the code fairly easily. My event handle function just needs to return a tuple of (body, statusCode, and headers)

**Comment by sloev** [comment]
@mcgodes can you maybe make a pr with some docs on this for README?
