### ISSUE TITLE
Remove py27 support since end-of-life

### ISSUE THREAD

**Issue by sloev** [trustpilot/python-lambdarest#53]
I wanna reach to to the users:

And ask whether you have anything against removing py27 support?

I am considering removing py27 support and bumping major version in next release 

@nabrosimoff 
@svdgraaf 
@devgrok 
@elviejokike
@simongarnier 
@eduardomourar

**Comment by svdgraaf** [comment]
Nope, we’re full on 3.7+ nowadays

**Comment by eduardomourar** [comment]
Running 3.6 as well, so no problem from our side.

**Comment by sloev** [comment]
i am dropping support for 

* python 2.7
* python 3.4

in https://github.com/trustpilot/python-lambdarest/pull/54

which releases Lambdarest==6.0.0

other changes:

* functools.wraps keeping the signature of functions
* readme changes
* cleanups, use black for linting etc

**Comment by sloev** [comment]
@nabrosimoff
@svdgraaf
@devgrok
@elviejokike
@simongarnier
@eduardomourar

version 6.0.0 is released.

changelog:

* drop support for python 2.7 and 3.4
* use functools.wraps for keeping of func signatures
* cleanup of repo, build, lint, and release process
