### ISSUE TITLE
Trouble installing with pip

### ISSUE THREAD

**Issue by zchesty** [trustpilot/python-lambdarest#56]
When running the install command "pip install lambdarest" I get an error 

 ERROR: Command errored out with exit status 1:
     command: /backend/api_lambda/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/65/jpxwzrxj68xb7lp74c2_yf8hrp6vql/T/pip-install-wor4aeh7/lambdarest/setup.py'"'"'; __file__='"'"'/private/var/folders/65/jpxwzrxj68xb7lp74c2_yf8hrp6vql/T/pip-install-wor4aeh7/lambdarest/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/65/jpxwzrxj68xb7lp74c2_yf8hrp6vql/T/pip-install-wor4aeh7/lambdarest/pip-egg-info
         cwd: /private/var/folders/65/jpxwzrxj68xb7lp74c2_yf8hrp6vql/T/pip-install-wor4aeh7/lambdarest/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/65/jpxwzrxj68xb7lp74c2_yf8hrp6vql/T/pip-install-wor4aeh7/lambdarest/setup.py", line 9, in <module>
        history = open("HISTORY.md").read()
    FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Is there an issue with the setup.py script? Is this a known issue?

**Comment by sloev** [comment]
I will fix and release today. Thx for notifying!!! There was a lot of
changes made and it looks like something exploded

tir. 28. jan. 2020 16.47 skrev Zachary Chestler <notifications@github.com>:

**Comment by sloev** [comment]
Yup. Its the manifest file missing a need for history.md

tir. 28. jan. 2020 17.59 skrev Johannes valbjørn <
johannes.valbjorn@gmail.com>:

**Comment by sloev** [comment]
it should be fixed in 6.0.1, can you try @zchesty?

**Comment by sloev** [comment]
Installing collected packages: strict-rfc3339, werkzeug, lambdarest
  Running setup.py install for strict-rfc3339 ... done
  Found existing installation: Werkzeug 0.15.5
    Uninstalling Werkzeug-0.15.5:
      Successfully uninstalled Werkzeug-0.15.5
  Running setup.py install for lambdarest ... done
Successfully installed lambdarest-6.0.1 strict-rfc3339-0.7 werkzeug-0.16.1

looks like it fixed it!

**Comment by zchesty** [comment]
thanks :)
