### ISSUE TITLE
[Question/BUG] Query Parameters converted to float

### ISSUE THREAD

**Issue by andyfase** [trustpilot/python-lambdarest#69]
# issue / feature request 

I Would like to understand the rationale of converting any query parameter that is a series of digits to floats. I am building an API that relies on Account ID's being based which are digits, these are needed in string form and python-lambdarest uses the `float()` function to convert all strings that are numeric, without the ability to override this behaviour from what i can tell. 

Is there a reason for this - HTTP is a string based protocol afaik, hence converting to float seems somewhat arbitrary and if needed something that could be done in business logic vs the underlying library which is parsing the API Gateway JSON payload.

Thanks!

**Comment by sloev** [comment]
Hi @andyfase just looked at the code. Seems like it was a too general catch all so i'm up for a change. 

Have you got time to make pseudocode, code + pr or a testcase that demonstrates your example?

Kind regards

**Comment by sloev** [comment]
Btw it only float casts arrays:

`value = list(map(__float_cast, value_cand))`

**Comment by sloev** [comment]
We could change it so it looks up the types from the input jsonschema and casts accordingly with a default on float-casting. That wouldnt strictly be backwards compatible so it would require a version bump

**Comment by andyfase** [comment]
Hey @sloev Indeed this is just for arrays, or multi-value query string parameters. Actually i wonder if this change can be made at the same time as potentially adding support for the `multiValueQueryStringParameters`  field within the event object. this field is supported for both API Gateway and ALB and its actually something I looked for in terms of support initially vs comma-seperation. This would allow for `foo&bar&foo=bar2` type query strings.

In this way comma-seperation float conversion can be left as is, and `multiValueQueryStringParameters` support can be added that either does not perform type casting or attempts to use the schema definition (if it exists) to convert to the appropriate type (string, integer, float) 

I'm happy to have a go at adding support for `multiValueQueryStringParameters` if you feel it's something you would accept.

**Comment by sloev** [comment]
If you give it a go it would be a great start. Then i have something to get going from. 

I've seen great contributions in this repo start with a testcase that demonstrates the issue, maybe we should start with that @andyfase ?

**Comment by sloev** [comment]
Nd to be clear:

I think hvaing support for *multi* is a need-to-have
But i would also argue thta the current json decoding behavior is wrong and should be using the jsonschema as tyoe register

**Comment by sloev** [comment]
@andyfase i have started work on this in here: https://github.com/trustpilot/python-lambdarest/pull/70

**Comment by sloev** [comment]
@andyfase https://github.com/trustpilot/python-lambdarest/pull/70 solves the issue with query params like this:

someurl?AccoundId=00012,2332300,fd000002,   120

which you can now specify to be treated as strings which will then be injected to your handler as:
def handler(...AccoundId):
    assert AccountID == ["00012", "2332300", "fd000002", "   120"

about **multiValueQueryStringParameters** lets to that in another pr: https://github.com/trustpilot/python-lambdarest/issues/71

**Comment by sloev** [comment]
its out

v.10.0.1

changes:

```
### 10.0.1 (2020-09-11)

**This is not a backwards compatible change.**

- Use query `schema.properties.query.properties.*` as type lookup for unpacking of query params to right types (including lists/singulars of strings/ints/floats/booleans)
- **not supporting json objects as values in query-params anymore** _use json body instead_ 
```
