### ISSUE TITLE
Versions prior to v13 on PyPI

### ISSUE THREAD

**Issue by stephane-berube** [trustpilot/python-lambdarest#94]
Hello,
  Our project has a dependency on "lambdarest==12.0.0" (which I do realize is old now) but was wondering if you were planning on publishing the previous versions of lambdarest on PyPI?

Thanks

**Comment by sloev** [comment]
hi, i am not gonna reup all old versions. 
I have tried for years to get a new maintainer for this project and lost my interest in maintaining it, but thought it was too risky to leave unmaintained so i reached out and told i was gonna take it down, noone replied so i took it down. Now today i got a donation to take it up again and further maintain it.

for old versions the closest you are gonna get is https://web.archive.org/web/20210922065429/https://pypi.org/project/lambdarest/#history it has up until 11.1


going onwards i am planning to commit 2 years to maintain it and try to find a co maintainer



For you specifically: from version 12 to 13 is nearly no code change, only reorg/reup of package plus some dep bumps

**Comment by stephane-berube** [comment]
Thank you, I appreciate the detailed reply
